version: '3'

services:
  db:
    image: postgres:9.5
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer:4.3
    ports:
      - 9000:8080